# Generated by Django 4.2.5 on 2023-10-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdrezkafilm',
            name='title_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hdrezkafilm',
            name='title_url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
