# Generated by Django 4.2.5 on 2023-09-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Укажите название: ')),
                ('description', models.TextField(verbose_name='Укажите описание наручных часов: ')),
                ('image', models.ImageField(upload_to='watch_photo/', verbose_name='Добавьте фото: ')),
                ('watch_type', models.CharField(choices=[('Мужские', 'Мужские'), ('Женские', 'Женские'), ('Унисекс', 'Унисекс')], max_length=70, verbose_name='Часы: ')),
                ('watch_type2', models.CharField(choices=[('Apple Watch', 'Apple Watch'), ('Casio', 'Casio'), ('Rolex', 'Rolex'), ('Cartier', 'Cartier'), ('Seiko', 'Seiko'), ('Made in China', 'Made in China')], max_length=70, verbose_name='Бренд часов: ')),
                ('cost', models.PositiveIntegerField(max_length=70, verbose_name='Укажите цену: ')),
                ('watch_location', models.CharField(max_length=70, verbose_name='Укажите местонахождение часов: ')),
                ('watch_url', models.URLField(verbose_name='Укажите ссылку: ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
