# Generated by Django 4.2.5 on 2023-09-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch',
            options={'verbose_name': 'Часы', 'verbose_name_plural': 'Часы'},
        ),
        migrations.AlterField(
            model_name='watch',
            name='cost',
            field=models.PositiveIntegerField(max_length=70, null=True, verbose_name='Укажите цену'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='description',
            field=models.TextField(null=True, verbose_name='Укажите описание наручных часов'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='image',
            field=models.ImageField(null=True, upload_to='watch_photo/', verbose_name='Добавьте фото'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='title',
            field=models.CharField(max_length=70, null=True, verbose_name='Укажите название'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='watch_location',
            field=models.CharField(max_length=70, null=True, verbose_name='Укажите местонахождение часов'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='watch_type',
            field=models.CharField(choices=[('Мужские', 'Мужские'), ('Женские', 'Женские'), ('Унисекс', 'Унисекс')], max_length=70, null=True, verbose_name='Часы'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='watch_type2',
            field=models.CharField(choices=[('Apple Watch', 'Apple Watch'), ('Casio', 'Casio'), ('Rolex', 'Rolex'), ('Cartier', 'Cartier'), ('Seiko', 'Seiko'), ('Made in China', 'Made in China')], max_length=70, null=True, verbose_name='Бренд часов'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='watch_url',
            field=models.URLField(null=True, verbose_name='Укажите ссылку'),
        ),
    ]
