# Generated by Django 4.2.5 on 2023-09-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0002_alter_watch_options_alter_watch_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Укажите описание наручных часов'),
        ),
        migrations.AlterField(
            model_name='watch',
            name='watch_type2',
            field=models.CharField(blank=True, choices=[('Apple Watch', 'Apple Watch'), ('Casio', 'Casio'), ('Rolex', 'Rolex'), ('Cartier', 'Cartier'), ('Seiko', 'Seiko'), ('Made in China', 'Made in China')], max_length=70, null=True, verbose_name='Бренд часов'),
        ),
    ]
