# Generated by Django 4.2.5 on 2023-09-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0003_alter_watch_description_alter_watch_watch_type2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='cost',
            field=models.PositiveIntegerField(null=True, verbose_name='Укажите цену'),
        ),
    ]
