# Generated by Django 4.2.5 on 2023-10-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_shop', '0007_remove_customuser_email_user_customuser_remeshok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type_card',
            field=models.IntegerField(choices=[(1, 'MBANK'), (2, 'QIWI'), (3, 'MASTERCARD'), (4, 'PAYPAL'), (5, 'VISA'), (6, 'MAESTRO'), (7, 'BTБ')], null=True, verbose_name='Тип карты'),
        ),
    ]
